Vagrant.configure("2") do |config|
  
  config.vm.define :master do |master|
	master.vm.box = "bento/ubuntu-22.04"
	master.vm.network :private_network, ip: "192.168.50.4"
	master.vm.hostname = "master"
  end
  
  config.vm.define :slave do |slave|
	slave.vm.box = "bento/ubuntu-22.04"
	slave.vm.network :private_network, ip: "192.168.50.5"
	slave.vm.hostname = "slave"
  end
  
  config.vm.define :client do |client|
	client.vm.box = "bento/ubuntu-22.04"
	client.vm.network :private_network, ip: "192.168.50.6"
	client.vm.hostname = "client"
  end
  
end
